# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kzdkm/文档/Hyprspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kzdkm/文档/Hyprspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kzdkm/文档/Hyprspace/CMakeFiles /home/kzdkm/文档/Hyprspace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kzdkm/文档/Hyprspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Hyprspace

# Build rule for target.
Hyprspace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hyprspace
.PHONY : Hyprspace

# fast build rule for target.
Hyprspace/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/build
.PHONY : Hyprspace/fast

CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

Hook/Hook.o: Hook/Hook.cpp.o
.PHONY : Hook/Hook.o

# target to build an object file
Hook/Hook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/Hook/Hook.cpp.o
.PHONY : Hook/Hook.cpp.o

Hook/Hook.i: Hook/Hook.cpp.i
.PHONY : Hook/Hook.i

# target to preprocess a source file
Hook/Hook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/Hook/Hook.cpp.i
.PHONY : Hook/Hook.cpp.i

Hook/Hook.s: Hook/Hook.cpp.s
.PHONY : Hook/Hook.s

# target to generate assembly for a file
Hook/Hook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/Hook/Hook.cpp.s
.PHONY : Hook/Hook.cpp.s

UI/Widget.o: UI/Widget.cpp.o
.PHONY : UI/Widget.o

# target to build an object file
UI/Widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/UI/Widget.cpp.o
.PHONY : UI/Widget.cpp.o

UI/Widget.i: UI/Widget.cpp.i
.PHONY : UI/Widget.i

# target to preprocess a source file
UI/Widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/UI/Widget.cpp.i
.PHONY : UI/Widget.cpp.i

UI/Widget.s: UI/Widget.cpp.s
.PHONY : UI/Widget.s

# target to generate assembly for a file
UI/Widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/UI/Widget.cpp.s
.PHONY : UI/Widget.cpp.s

build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.o: build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.i: build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.s: build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hyprspace.dir/build.make CMakeFiles/Hyprspace.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Hyprspace"
	@echo "... CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... Hook/Hook.o"
	@echo "... Hook/Hook.i"
	@echo "... Hook/Hook.s"
	@echo "... UI/Widget.o"
	@echo "... UI/Widget.i"
	@echo "... UI/Widget.s"
	@echo "... build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... build/CMakeFiles/3.29.0/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

